# Ejemplo 1 - Scraping tabla

In [1]:
import tabula
import pandas as pd

df=tabula.read_pdf("ProctorTesting.pdf", pages="13") #selecciono hoja
df1=df[0] #primera tabla
df1

,Sieve\rSize,Part\rDiam\r(mm),Gravel,Unnamed: 0,Fine\rSand,Sandy\rSilt,Loess,Loess/\rTill,Till,Shale
0,4,4.760,79.5,NaN,100.0,100.0,100.0,100.0,100.0,100.0
1,10,2.000,56.8,NaN,98.0,99.8,100.0,100.0,100.0,100.0
2,16,0.840,34.4,NaN,91.4,97.5,98.9,98.2,98.6,100.0
3,40,0.420,17.5,NaN,66.4,76.7,93.3,88.2,84.4,96.6
4,100,0.149,2.3,NaN,25.1,50.3,82.6,70.9,61.4,87.9
5,200,0.074,0.3,NaN,16.3,44.4,78.2,61.4,52.8,82.5
6,Pan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df1 = df1.drop("Unnamed: 0", axis=1)
df1

,Sieve\rSize,Part\rDiam\r(mm),Gravel,Fine\rSand,Sandy\rSilt,Loess,Loess/\rTill,Till,Shale
0,4,4.760,79.5,100.0,100.0,100.0,100.0,100.0,100.0
1,10,2.000,56.8,98.0,99.8,100.0,100.0,100.0,100.0
2,16,0.840,34.4,91.4,97.5,98.9,98.2,98.6,100.0
3,40,0.420,17.5,66.4,76.7,93.3,88.2,84.4,96.6
4,100,0.149,2.3,25.1,50.3,82.6,70.9,61.4,87.9
5,200,0.074,0.3,16.3,44.4,78.2,61.4,52.8,82.5
6,Pan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Ejemplo 2 - Scraping de texto

In [3]:
import PyPDF2

pdfFileObj = open('ProctorTesting.pdf', 'rb')

pdfReader = PyPDF2.PdfFileReader(pdfFileObj)

pageObj = pdfReader.getPage(0)  # primera hoja

print(pageObj.extractText())

# cerrar carpeta
texto_extraido=pdfFileObj.close()

texto_extraido

University of Nebraska - Lincoln
DigitalCommons@University of Nebraska - Lincoln
Nebraska Department of Transportation Research
Reports Nebraska LTAP
5-2008
Proctor Compaction Testing
Joshua Connelly
Wayne Jensen
University of Nebraska - Lincoln, wayne.jensen@unl.edu
Paul Harmon
University of Nebraska - Lincoln
Follow this and additional works at:http://digitalcommons.unl.edu/ndor

Part of theTransportation Engineering Commons
This Article is brought to you for free and open access by the Nebraska LTAP at DigitalCommons@University of Nebraska - Lincoln. It has been
accepted for inclusion in Nebraska Department of Transportation Research Reports by an authorized administrator of DigitalCommons@University of
Nebraska - Lincoln.Connelly, Joshua; Jensen, Wayne; and Harmon, Paul, "Proctor Compaction Testing" (2008).Nebraska Department of Transportation
Research Reports. 31.
http://digitalcommons.unl.edu/ndor/31

# Ejemplo 3 - Scraping tabla de PDF

In [4]:
ejemplo3=tabula.read_pdf("ejemplo.pdf")
ejemplo3b=ejemplo3[0]
ejemplo3b

'pages' argument isn't specified.Will extract only from page 1 by default.

,RÍO: DEL VALLE,CUENCA: la Falda Oriental del Ambato,Unnamed: 0,Unnamed: 1,"LONGITUD: 065° 47' 53.40""",Unnamed: 2
0,LUGAR: HUAYCAMA,NaN,NaN,NaN,ÁREA(km2): ---,NaN
1,PROVINCIA: Catamarca,NaN,NaN,NaN,ALTITUD(msnm): 937,NaN
2,Caudal Escala Caudal,Ancho Perímetro,Velocidad Velocidad,Incertidumbre,Caudal Incertidumbre,NaN
3,Sólido Fecha Hora Media Líquido,Área Superficial Mojado,Media Máxima,Total,Sólido Aleatoria,NaN
4,NaN,[m2],NaN,NaN,Fino,Grueso
5,[m] [m3/seg],[m] [m],[m/seg] [m/seg],[%],[%],NaN
6,NaN,NaN,NaN,NaN,[kg/seg],[kg/seg]
7,09/06/2010 15:35 1.05 1.7,6.5 15.4 15.7,0.26 0.43,16.0,15.9 0.0,0.0
8,06/07/2010 14:20 1.03 1.6,7.5 22.5 22.7,0.22 0.30,15.9,15.9 0.0,0.0
9,17/08/2010 12:00 1.01 1.7,7.2 22.5 22.7,0.23 0.30,15.9,15.8 0.0,0.0
10,16/09/2010 14:30 0.99 1.7,7.0 22.0 22.1,0.24 0.29,15.5,15.5 0.0,0.0
11,14/10/2010 15:30 0.97 1.3,6.5 21.5 21.6,0.21 0.24,15.6,15.5 0.0,0.0
12,19/11/2010 14:20 0.95 0.9,5.9 21.0 21.1,0.15 0.18,15.7,15.7 0.0,0.0
13,10/12/2010 13:30 1.03 1.1,2.9 7.5 7.9,0.40 0.69,15.8,15.7 0.1,0.0
14,12/01/2011 13:30 1.10 2.4,5.1 11.2 11.9,0.46 0.76,15.6,15.6 0.1,0.1
15,11/02/2011 09:20 1.66 16.9,17.8 22.5 22.9,0.95 1.76,11.7,11.7 2.4,0.7
16,03/03/2011 11:10 1.50 12.4,15.8 22.3 22.6,0.78 1.16,12.9,12.9 0.3,0.1
17,19/04/2011 16:10 1.19 5.3,9.5 22.5 22.6,0.56 0.67,15.8,15.8 0.1,0.0
18,18/05/2011 18:10 1.11 4.3,8.2 21.0 21.1,0.52 0.66,15.6,15.5 0.0,0.0
19,15/06/2011 10:00 1.06 3.4,7.2 20.5 20.6,0.47 0.56,15.5,15.5 0.0,0.0
20,07/07/2011 19:20 1.05 1.5,5.1 11.5 12.0,0.30 0.46,15.5,15.5 0.0,0.0
21,10/08/2011 14:00 1.03 2.9,6.6 20.3 20.4,0.43 0.52,15.5,15.5 0.0,0.0
22,14/09/2011 17:00 1.01 2.5,6.2 20.0 20.1,0.40 0.49,15.6,15.5 0.0,0.0
23,18/10/2011 09:55 0.99 2.1,5.9 19.7 19.8,0.36 0.46,15.6,15.5 0.0,0.0
24,03/11/2011 15:30 0.98 1.9,5.7 19.5 19.6,0.34 0.40,15.6,15.6 0.0,0.0
25,05/12/2011 09:40 1.48 11.8,14.4 21.0 21.4,0.82 1.09,15.0,15.0 16.0,0.6
26,23/01/2012 09:40 1.21 5.6,9.6 19.0 19.2,0.59 0.79,15.5,15.4 0.3,0.1
27,02/02/2012 09:00 1.48 11.4,13.8 20.8 21.0,0.82 0.98,15.6,15.6 1.5,0.4
28,13/03/2012 09:40 1.20 5.3,9.9 20.0 20.1,0.54 0.71,15.4,15.4 0.0,0.0
29,25/04/2012 09:50 1.12 4.3,8.6 19.5 19.6,0.50 0.66,15.5,15.4 0.0,0.0
30,26/05/2012 17:00 1.09 3.9,8.0 19.5 19.6,0.48 0.64,15.4,15.4 0.0,0.0

In [5]:
ejemplo3l= ejemplo3b.dropna() #elimino nan para poder trabajar con los datos primero

In [6]:
ejemplo3l.columns = ['col1', 'col2', 'col3', 'col4', 'col5', 'col6'] #transformo las columnas para luego trabajar sus nombres a parte
ejemplo3l.columns = ejemplo3l.columns.str.replace('col4', 'Incertidumbre total')
ejemplo3l.columns = ejemplo3l.columns.str.replace('col6', 'Caudal sólido grueso')
ejemplo3l

,col1,col2,col3,Incertidumbre total,col5,Caudal sólido grueso
7,09/06/2010 15:35 1.05 1.7,6.5 15.4 15.7,0.26 0.43,16.0,15.9 0.0,0.0
8,06/07/2010 14:20 1.03 1.6,7.5 22.5 22.7,0.22 0.30,15.9,15.9 0.0,0.0
9,17/08/2010 12:00 1.01 1.7,7.2 22.5 22.7,0.23 0.30,15.9,15.8 0.0,0.0
10,16/09/2010 14:30 0.99 1.7,7.0 22.0 22.1,0.24 0.29,15.5,15.5 0.0,0.0
11,14/10/2010 15:30 0.97 1.3,6.5 21.5 21.6,0.21 0.24,15.6,15.5 0.0,0.0
12,19/11/2010 14:20 0.95 0.9,5.9 21.0 21.1,0.15 0.18,15.7,15.7 0.0,0.0
13,10/12/2010 13:30 1.03 1.1,2.9 7.5 7.9,0.40 0.69,15.8,15.7 0.1,0.0
14,12/01/2011 13:30 1.10 2.4,5.1 11.2 11.9,0.46 0.76,15.6,15.6 0.1,0.1
15,11/02/2011 09:20 1.66 16.9,17.8 22.5 22.9,0.95 1.76,11.7,11.7 2.4,0.7
16,03/03/2011 11:10 1.50 12.4,15.8 22.3 22.6,0.78 1.16,12.9,12.9 0.3,0.1
17,19/04/2011 16:10 1.19 5.3,9.5 22.5 22.6,0.56 0.67,15.8,15.8 0.1,0.0
18,18/05/2011 18:10 1.11 4.3,8.2 21.0 21.1,0.52 0.66,15.6,15.5 0.0,0.0
19,15/06/2011 10:00 1.06 3.4,7.2 20.5 20.6,0.47 0.56,15.5,15.5 0.0,0.0
20,07/07/2011 19:20 1.05 1.5,5.1 11.5 12.0,0.30 0.46,15.5,15.5 0.0,0.0
21,10/08/2011 14:00 1.03 2.9,6.6 20.3 20.4,0.43 0.52,15.5,15.5 0.0,0.0
22,14/09/2011 17:00 1.01 2.5,6.2 20.0 20.1,0.40 0.49,15.6,15.5 0.0,0.0
23,18/10/2011 09:55 0.99 2.1,5.9 19.7 19.8,0.36 0.46,15.6,15.5 0.0,0.0
24,03/11/2011 15:30 0.98 1.9,5.7 19.5 19.6,0.34 0.40,15.6,15.6 0.0,0.0
25,05/12/2011 09:40 1.48 11.8,14.4 21.0 21.4,0.82 1.09,15.0,15.0 16.0,0.6
26,23/01/2012 09:40 1.21 5.6,9.6 19.0 19.2,0.59 0.79,15.5,15.4 0.3,0.1
27,02/02/2012 09:00 1.48 11.4,13.8 20.8 21.0,0.82 0.98,15.6,15.6 1.5,0.4
28,13/03/2012 09:40 1.20 5.3,9.9 20.0 20.1,0.54 0.71,15.4,15.4 0.0,0.0
29,25/04/2012 09:50 1.12 4.3,8.6 19.5 19.6,0.50 0.66,15.5,15.4 0.0,0.0
30,26/05/2012 17:00 1.09 3.9,8.0 19.5 19.6,0.48 0.64,15.4,15.4 0.0,0.0

In [7]:
ejemplo3l[['Fecha', 'Hora', 'Escala Media', 'Caudal líquido']] = ejemplo3l['col1'].str.split(' ', expand=True)
ejemplo3l[['Area', 'Perimetro Sup', 'Perímetro mojado']] = ejemplo3l['col2'].str.split(' ', expand=True)
ejemplo3l[['Vel media', 'Vel máxima']] = ejemplo3l['col3'].str.split(' ', expand=True)
ejemplo3l[['Incertidumbre aleatoria', 'Caudal fino']] = ejemplo3l['col5'].str.split(' ', expand=True)

coleliminar = ['col1', 'col2', 'col3', 'col5']
ejemplo3l=ejemplo3l.drop(columns=coleliminar)
ejemplo3l

C:\Users\flore\AppData\Local\Temp\ipykernel_18588\1739954509.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ejemplo3l[['Fecha', 'Hora', 'Escala Media', 'Caudal líquido']] = ejemplo3l['col1'].str.split(' ', expand=True)
C:\Users\flore\AppData\Local\Temp\ipykernel_18588\1739954509.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ejemplo3l[['Fecha', 'Hora', 'Escala Media', 'Caudal líquido']] = ejemplo3l['col1'].str.split(' ', expand=True)
C:\Users\flore\AppData\Local\Temp\ipykernel_18588\1739954509.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ejemplo3l[['Fecha', 'Hora', 'Escala Media', 'Caudal líquido']] = ejemplo3l['col1'].str.split(' ', expand=True)
C:\Users\flore\AppData\Local\Temp\ipykernel_18588\1739954509.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ejemplo3l[['Fecha', 'Hora', 'Escala Media', 'Caudal líquido']] = ejemplo3l['col1'].str.split(' ', expand=True)
C:\Users\flore\AppData\Local\Temp\ipykernel_18588\1739954509.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ejemplo3l[['Area', 'Perimetro Sup', 'Perímetro mojado']] = ejemplo3l['col2'].str.split(' ', expand=True)
C:\Users\flore\AppData\Local\Temp\ipykernel_18588\1739954509.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ejemplo3l[['Area', 'Perimetro Sup', 'Perímetro mojado']] = ejemplo3l['col2'].str.split(' ', expand=True)
C:\Users\flore\AppData\Local\Temp\ipykernel_18588\1739954509.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ejemplo3l[['Area', 'Perimetro Sup', 'Perímetro mojado']] = ejemplo3l['col2'].str.split(' ', expand=True)
C:\Users\flore\AppData\Local\Temp\ipykernel_18588\1739954509.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ejemplo3l[['Vel media', 'Vel máxima']] = ejemplo3l['col3'].str.split(' ', expand=True)
C:\Users\flore\AppData\Local\Temp\ipykernel_18588\1739954509.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ejemplo3l[['Vel media', 'Vel máxima']] = ejemplo3l['col3'].str.split(' ', expand=True)
C:\Users\flore\AppData\Local\Temp\ipykernel_18588\1739954509.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ejemplo3l[['Incertidumbre aleatoria', 'Caudal fino']] = ejemplo3l['col5'].str.split(' ', expand=True)
C:\Users\flore\AppData\Local\Temp\ipykernel_18588\1739954509.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ejemplo3l[['Incertidumbre aleatoria', 'Caudal fino']] = ejemplo3l['col5'].str.split(' ', expand=True)

,Incertidumbre total,Caudal sólido grueso,Fecha,Hora,Escala Media,Caudal líquido,Area,Perimetro Sup,Perímetro mojado,Vel media,Vel máxima,Incertidumbre aleatoria,Caudal fino
7,16.0,0.0,09/06/2010,15:35,1.05,1.7,6.5,15.4,15.7,0.26,0.43,15.9,0.0
8,15.9,0.0,06/07/2010,14:20,1.03,1.6,7.5,22.5,22.7,0.22,0.30,15.9,0.0
9,15.9,0.0,17/08/2010,12:00,1.01,1.7,7.2,22.5,22.7,0.23,0.30,15.8,0.0
10,15.5,0.0,16/09/2010,14:30,0.99,1.7,7.0,22.0,22.1,0.24,0.29,15.5,0.0
11,15.6,0.0,14/10/2010,15:30,0.97,1.3,6.5,21.5,21.6,0.21,0.24,15.5,0.0
12,15.7,0.0,19/11/2010,14:20,0.95,0.9,5.9,21.0,21.1,0.15,0.18,15.7,0.0
13,15.8,0.0,10/12/2010,13:30,1.03,1.1,2.9,7.5,7.9,0.40,0.69,15.7,0.1
14,15.6,0.1,12/01/2011,13:30,1.10,2.4,5.1,11.2,11.9,0.46,0.76,15.6,0.1
15,11.7,0.7,11/02/2011,09:20,1.66,16.9,17.8,22.5,22.9,0.95,1.76,11.7,2.4
16,12.9,0.1,03/03/2011,11:10,1.50,12.4,15.8,22.3,22.6,0.78,1.16,12.9,0.3
17,15.8,0.0,19/04/2011,16:10,1.19,5.3,9.5,22.5,22.6,0.56,0.67,15.8,0.1
18,15.6,0.0,18/05/2011,18:10,1.11,4.3,8.2,21.0,21.1,0.52,0.66,15.5,0.0
19,15.5,0.0,15/06/2011,10:00,1.06,3.4,7.2,20.5,20.6,0.47,0.56,15.5,0.0
20,15.5,0.0,07/07/2011,19:20,1.05,1.5,5.1,11.5,12.0,0.30,0.46,15.5,0.0
21,15.5,0.0,10/08/2011,14:00,1.03,2.9,6.6,20.3,20.4,0.43,0.52,15.5,0.0
22,15.6,0.0,14/09/2011,17:00,1.01,2.5,6.2,20.0,20.1,0.40,0.49,15.5,0.0
23,15.6,0.0,18/10/2011,09:55,0.99,2.1,5.9,19.7,19.8,0.36,0.46,15.5,0.0
24,15.6,0.0,03/11/2011,15:30,0.98,1.9,5.7,19.5,19.6,0.34,0.40,15.6,0.0
25,15.0,0.6,05/12/2011,09:40,1.48,11.8,14.4,21.0,21.4,0.82,1.09,15.0,16.0
26,15.5,0.1,23/01/2012,09:40,1.21,5.6,9.6,19.0,19.2,0.59,0.79,15.4,0.3
27,15.6,0.4,02/02/2012,09:00,1.48,11.4,13.8,20.8,21.0,0.82,0.98,15.6,1.5
28,15.4,0.0,13/03/2012,09:40,1.20,5.3,9.9,20.0,20.1,0.54,0.71,15.4,0.0
29,15.5,0.0,25/04/2012,09:50,1.12,4.3,8.6,19.5,19.6,0.50,0.66,15.4,0.0
30,15.4,0.0,26/05/2012,17:00,1.09,3.9,8.0,19.5,19.6,0.48,0.64,15.4,0.0

In [8]:
ejemplo3l[ejemplo3l.columns[-1]] = ejemplo3l.pop(ejemplo3l.columns[0])

In [10]:
ejemplo3l[ejemplo3l.columns[-2]] = ejemplo3l.pop(ejemplo3l.columns[0])
ejemplo3l

,Hora,Escala Media,Caudal líquido,Area,Perimetro Sup,Perímetro mojado,Vel media,Vel máxima,Incertidumbre aleatoria,Caudal fino
7,15:35,1.05,1.7,6.5,15.4,15.7,0.26,0.43,09/06/2010,16.0
8,14:20,1.03,1.6,7.5,22.5,22.7,0.22,0.30,06/07/2010,15.9
9,12:00,1.01,1.7,7.2,22.5,22.7,0.23,0.30,17/08/2010,15.9
10,14:30,0.99,1.7,7.0,22.0,22.1,0.24,0.29,16/09/2010,15.5
11,15:30,0.97,1.3,6.5,21.5,21.6,0.21,0.24,14/10/2010,15.6
12,14:20,0.95,0.9,5.9,21.0,21.1,0.15,0.18,19/11/2010,15.7
13,13:30,1.03,1.1,2.9,7.5,7.9,0.40,0.69,10/12/2010,15.8
14,13:30,1.10,2.4,5.1,11.2,11.9,0.46,0.76,12/01/2011,15.6
15,09:20,1.66,16.9,17.8,22.5,22.9,0.95,1.76,11/02/2011,11.7
16,11:10,1.50,12.4,15.8,22.3,22.6,0.78,1.16,03/03/2011,12.9
17,16:10,1.19,5.3,9.5,22.5,22.6,0.56,0.67,19/04/2011,15.8
18,18:10,1.11,4.3,8.2,21.0,21.1,0.52,0.66,18/05/2011,15.6
19,10:00,1.06,3.4,7.2,20.5,20.6,0.47,0.56,15/06/2011,15.5
20,19:20,1.05,1.5,5.1,11.5,12.0,0.30,0.46,07/07/2011,15.5
21,14:00,1.03,2.9,6.6,20.3,20.4,0.43,0.52,10/08/2011,15.5
22,17:00,1.01,2.5,6.2,20.0,20.1,0.40,0.49,14/09/2011,15.6
23,09:55,0.99,2.1,5.9,19.7,19.8,0.36,0.46,18/10/2011,15.6
24,15:30,0.98,1.9,5.7,19.5,19.6,0.34,0.40,03/11/2011,15.6
25,09:40,1.48,11.8,14.4,21.0,21.4,0.82,1.09,05/12/2011,15.0
26,09:40,1.21,5.6,9.6,19.0,19.2,0.59,0.79,23/01/2012,15.5
27,09:00,1.48,11.4,13.8,20.8,21.0,0.82,0.98,02/02/2012,15.6
28,09:40,1.20,5.3,9.9,20.0,20.1,0.54,0.71,13/03/2012,15.4
29,09:50,1.12,4.3,8.6,19.5,19.6,0.50,0.66,25/04/2012,15.5
30,17:00,1.09,3.9,8.0,19.5,19.6,0.48,0.64,26/05/2012,15.4